// <auto-generated />
namespace Farfetch.Buildionaire.Data.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Badges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Badges));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091244326_Badges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
